# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PsctRunControlMainWindow(object):
    def setupUi(self, PsctRunControlMainWindow):
        PsctRunControlMainWindow.setObjectName("PsctRunControlMainWindow")
        PsctRunControlMainWindow.resize(1069, 887)
        self.centralwidget = QtWidgets.QWidget(PsctRunControlMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.connected_led = LED(self.centralwidget)
        self.connected_led.setObjectName("connected_led")
        self.gridLayout.addWidget(self.connected_led, 0, 2, 1, 1)
        self.log_textbrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.log_textbrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.log_textbrowser.setObjectName("log_textbrowser")
        self.gridLayout.addWidget(self.log_textbrowser, 23, 0, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 21, 0, 1, 1)
        self.config_file_widgets = QtWidgets.QHBoxLayout()
        self.config_file_widgets.setObjectName("config_file_widgets")
        self.load_config_button = QtWidgets.QPushButton(self.centralwidget)
        self.load_config_button.setEnabled(True)
        self.load_config_button.setMaximumSize(QtCore.QSize(116, 16777215))
        font = QtGui.QFont()
        font.setKerning(False)
        self.load_config_button.setFont(font)
        self.load_config_button.setObjectName("load_config_button")
        self.config_file_widgets.addWidget(self.load_config_button)
        self.config_path_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.config_path_dropdown.setObjectName("config_path_dropdown")
        self.config_file_widgets.addWidget(self.config_path_dropdown)
        self.gridLayout.addLayout(self.config_file_widgets, 0, 0, 1, 1)
        self.config_textbrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.config_textbrowser.setEnabled(True)
        self.config_textbrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.config_textbrowser.setObjectName("config_textbrowser")
        self.gridLayout.addWidget(self.config_textbrowser, 1, 0, 7, 1)
        self.apply_button = QtWidgets.QPushButton(self.centralwidget)
        self.apply_button.setCheckable(False)
        self.apply_button.setObjectName("apply_button")
        self.gridLayout.addWidget(self.apply_button, 2, 1, 1, 2)
        self.initialize_button = QtWidgets.QPushButton(self.centralwidget)
        self.initialize_button.setObjectName("initialize_button")
        self.gridLayout.addWidget(self.initialize_button, 4, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.shutdown_button = QtWidgets.QPushButton(self.centralwidget)
        self.shutdown_button.setObjectName("shutdown_button")
        self.gridLayout.addWidget(self.shutdown_button, 5, 1, 1, 2)
        self.apply_status_textbox = QtWidgets.QLabel(self.centralwidget)
        self.apply_status_textbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.apply_status_textbox.setIndent(10)
        self.apply_status_textbox.setObjectName("apply_status_textbox")
        self.gridLayout.addWidget(self.apply_status_textbox, 3, 1, 1, 1)
        self.run_widgets = QtWidgets.QGridLayout()
        self.run_widgets.setObjectName("run_widgets")
        self.run_progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.run_progress_bar.setProperty("value", 24)
        self.run_progress_bar.setObjectName("run_progress_bar")
        self.run_widgets.addWidget(self.run_progress_bar, 2, 1, 1, 4)
        self.remaining_time_textbox = QtWidgets.QLabel(self.centralwidget)
        self.remaining_time_textbox.setMaximumSize(QtCore.QSize(29, 16777215))
        self.remaining_time_textbox.setObjectName("remaining_time_textbox")
        self.run_widgets.addWidget(self.remaining_time_textbox, 2, 5, 1, 1)
        self.elapsed_time_textbox = QtWidgets.QLabel(self.centralwidget)
        self.elapsed_time_textbox.setMaximumSize(QtCore.QSize(29, 16777215))
        self.elapsed_time_textbox.setObjectName("elapsed_time_textbox")
        self.run_widgets.addWidget(self.elapsed_time_textbox, 2, 0, 1, 1)
        self.stop_run_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_run_button.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.stop_run_button.setFont(font)
        self.stop_run_button.setAutoFillBackground(False)
        self.stop_run_button.setObjectName("stop_run_button")
        self.run_widgets.addWidget(self.stop_run_button, 0, 4, 1, 1)
        self.add_comments = QtWidgets.QPushButton(self.centralwidget)
        self.add_comments.setObjectName("add_comments")
        self.run_widgets.addWidget(self.add_comments, 0, 3, 1, 1)
        self.start_run_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_run_button.setObjectName("start_run_button")
        self.run_widgets.addWidget(self.start_run_button, 0, 2, 1, 1)
        self.define_run = QtWidgets.QPushButton(self.centralwidget)
        self.define_run.setObjectName("define_run")
        self.run_widgets.addWidget(self.define_run, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.run_widgets.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.run_widgets.addWidget(self.label_3, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.run_widgets, 19, 0, 2, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 5, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setVisible(True)
        self.gridLayout.addWidget(self.tableWidget, 10, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        PsctRunControlMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PsctRunControlMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1069, 24))
        self.menubar.setObjectName("menubar")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        PsctRunControlMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PsctRunControlMainWindow)
        self.statusbar.setObjectName("statusbar")
        PsctRunControlMainWindow.setStatusBar(self.statusbar)
        self.actionConfigure_Modules = QtWidgets.QAction(PsctRunControlMainWindow)
        self.actionConfigure_Modules.setObjectName("actionConfigure_Modules")
        self.actionSend_Single_Command = QtWidgets.QAction(PsctRunControlMainWindow)
        self.actionSend_Single_Command.setObjectName("actionSend_Single_Command")
        self.action_new_conf = QtWidgets.QAction(PsctRunControlMainWindow)
        self.action_new_conf.setObjectName("action_new_conf")
        self.action_open_conf = QtWidgets.QAction(PsctRunControlMainWindow)
        self.action_open_conf.setObjectName("action_open_conf")
        self.action_save_conf = QtWidgets.QAction(PsctRunControlMainWindow)
        self.action_save_conf.setObjectName("action_save_conf")
        self.action_save_conf_as = QtWidgets.QAction(PsctRunControlMainWindow)
        self.action_save_conf_as.setObjectName("action_save_conf_as")
        self.actionTriggerConf = QtWidgets.QAction(PsctRunControlMainWindow)
        self.actionTriggerConf.setObjectName("actionTriggerConf")
        self.actionModule_Config = QtWidgets.QAction(PsctRunControlMainWindow)
        self.actionModule_Config.setObjectName("actionModule_Config")
        self.action_mod_config = QtWidgets.QAction(PsctRunControlMainWindow)
        self.action_mod_config.setObjectName("action_mod_config")
        self.action_diagnostic_view = QtWidgets.QAction(PsctRunControlMainWindow)
        self.action_diagnostic_view.setObjectName("action_diagnostic_view")
        self.menuTools.addAction(self.action_mod_config)
        self.menuTools.addAction(self.action_diagnostic_view)
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(PsctRunControlMainWindow)
        QtCore.QMetaObject.connectSlotsByName(PsctRunControlMainWindow)

    def retranslateUi(self, PsctRunControlMainWindow):
        _translate = QtCore.QCoreApplication.translate
        PsctRunControlMainWindow.setWindowTitle(_translate("PsctRunControlMainWindow", "SCT Run Control"))
        self.label_4.setText(_translate("PsctRunControlMainWindow", "Messages"))
        self.load_config_button.setText(_translate("PsctRunControlMainWindow", "Load Config"))
        self.apply_button.setText(_translate("PsctRunControlMainWindow", "Apply Config"))
        self.initialize_button.setText(_translate("PsctRunControlMainWindow", "Initialize"))
        self.label.setText(_translate("PsctRunControlMainWindow", "Connected"))
        self.shutdown_button.setText(_translate("PsctRunControlMainWindow", "Shutdown"))
        self.apply_status_textbox.setText(_translate("PsctRunControlMainWindow", "NOT APPLIED"))
        self.remaining_time_textbox.setText(_translate("PsctRunControlMainWindow", "--/--"))
        self.elapsed_time_textbox.setText(_translate("PsctRunControlMainWindow", "--/--"))
        self.stop_run_button.setText(_translate("PsctRunControlMainWindow", "Stop Run"))
        self.add_comments.setText(_translate("PsctRunControlMainWindow", "Add Comments"))
        self.start_run_button.setText(_translate("PsctRunControlMainWindow", "Start Run"))
        self.define_run.setText(_translate("PsctRunControlMainWindow", "Define Run"))
        self.label_2.setText(_translate("PsctRunControlMainWindow", "Elapsed:"))
        self.label_3.setText(_translate("PsctRunControlMainWindow", "Remaining:"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("PsctRunControlMainWindow", "Status"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("PsctRunControlMainWindow", "Run ID"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("PsctRunControlMainWindow", "Source"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("PsctRunControlMainWindow", "Weather"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("PsctRunControlMainWindow", "Duration"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("PsctRunControlMainWindow", "Run type"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.menuTools.setTitle(_translate("PsctRunControlMainWindow", "Tools"))
        self.actionConfigure_Modules.setText(_translate("PsctRunControlMainWindow", "Configure Modules"))
        self.actionSend_Single_Command.setText(_translate("PsctRunControlMainWindow", "Send Single Command"))
        self.action_new_conf.setText(_translate("PsctRunControlMainWindow", "New Configuration"))
        self.action_open_conf.setText(_translate("PsctRunControlMainWindow", "Open"))
        self.action_save_conf.setText(_translate("PsctRunControlMainWindow", "Save"))
        self.action_save_conf_as.setText(_translate("PsctRunControlMainWindow", "Save As"))
        self.actionTriggerConf.setText(_translate("PsctRunControlMainWindow", "Trigger Configuration"))
        self.actionModule_Config.setText(_translate("PsctRunControlMainWindow", "Module Configuration"))
        self.action_mod_config.setText(_translate("PsctRunControlMainWindow", "Module Configuration"))
        self.action_diagnostic_view.setText(_translate("PsctRunControlMainWindow", "Diagnostic View"))
from sctcamsoft.lib_gui.led import LED
