# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1192, 987)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(650, 20, 521, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.splitter = QtWidgets.QSplitter(self.frame_4)
        self.splitter.setGeometry(QtCore.QRect(15, 20, 501, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.splitter.setFont(font)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_3 = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self._led1 = LED(self.splitter)
        self._led1.setMaximumSize(QtCore.QSize(16777215, 25))
        self._led1.setObjectName("_led1")
        self.sysInitializeButton = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sysInitializeButton.setFont(font)
        self.sysInitializeButton.setObjectName("sysInitializeButton")
        self.sysShutdownButton = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sysShutdownButton.setFont(font)
        self.sysShutdownButton.setObjectName("sysShutdownButton")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(650, 480, 521, 121))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.shutter_control_groupbox = QtWidgets.QGroupBox(self.frame_5)
        self.shutter_control_groupbox.setGeometry(QtCore.QRect(10, 0, 501, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shutter_control_groupbox.sizePolicy().hasHeightForWidth())
        self.shutter_control_groupbox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.shutter_control_groupbox.setFont(font)
        self.shutter_control_groupbox.setObjectName("shutter_control_groupbox")
        self.pushButton_6 = QtWidgets.QPushButton(self.shutter_control_groupbox)
        self.pushButton_6.setGeometry(QtCore.QRect(9, 33, 94, 29))
        self.pushButton_6.setObjectName("pushButton_6")
        self.frame = QtWidgets.QFrame(self.shutter_control_groupbox)
        self.frame.setGeometry(QtCore.QRect(110, 30, 131, 61))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.shutter_control_groupbox)
        self.frame_2.setGeometry(QtCore.QRect(250, 30, 181, 61))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.shutter_control_groupbox)
        self.pushButton_7.setGeometry(QtCore.QRect(9, 64, 94, 29))
        self.pushButton_7.setObjectName("pushButton_7")
        self.progressBar = QtWidgets.QProgressBar(self.shutter_control_groupbox)
        self.progressBar.setGeometry(QtCore.QRect(450, 30, 21, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.progressBar.setMaximum(6)
        self.progressBar.setProperty("value", 1)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Vertical)
        self.progressBar.setInvertedAppearance(True)
        self.progressBar.setObjectName("progressBar")
        self.frame_2.raise_()
        self.frame.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.progressBar.raise_()
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 780, 1161, 171))
        self.textBrowser.setObjectName("textBrowser")
        self.chiller_frame = QtWidgets.QFrame(self.centralwidget)
        self.chiller_frame.setEnabled(True)
        self.chiller_frame.setGeometry(QtCore.QRect(390, 600, 391, 171))
        self.chiller_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chiller_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chiller_frame.setObjectName("chiller_frame")
        self.chiller_groupbox = QtWidgets.QGroupBox(self.chiller_frame)
        self.chiller_groupbox.setGeometry(QtCore.QRect(10, 10, 371, 141))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.chiller_groupbox.setFont(font)
        self.chiller_groupbox.setTitle("")
        self.chiller_groupbox.setObjectName("chiller_groupbox")
        self.layoutWidget = QtWidgets.QWidget(self.chiller_groupbox)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 30, 341, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.chiller_pressure_label = QtWidgets.QLabel(self.layoutWidget)
        self.chiller_pressure_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.chiller_pressure_label.setAlignment(QtCore.Qt.AlignCenter)
        self.chiller_pressure_label.setObjectName("chiller_pressure_label")
        self.gridLayout.addWidget(self.chiller_pressure_label, 0, 0, 1, 1)
        self.chiller_temp_label = QtWidgets.QLabel(self.layoutWidget)
        self.chiller_temp_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.chiller_temp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.chiller_temp_label.setObjectName("chiller_temp_label")
        self.gridLayout.addWidget(self.chiller_temp_label, 0, 1, 1, 1)
        self.chiller_pressure_lineedit = QtWidgets.QLineEdit(self.layoutWidget)
        self.chiller_pressure_lineedit.setReadOnly(True)
        self.chiller_pressure_lineedit.setObjectName("chiller_pressure_lineedit")
        self.gridLayout.addWidget(self.chiller_pressure_lineedit, 1, 0, 1, 1)
        self.chiller_temp_lineedit = QtWidgets.QLineEdit(self.layoutWidget)
        self.chiller_temp_lineedit.setReadOnly(True)
        self.chiller_temp_lineedit.setObjectName("chiller_temp_lineedit")
        self.gridLayout.addWidget(self.chiller_temp_lineedit, 1, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.chiller_frame)
        self.label_33.setGeometry(QtCore.QRect(20, 0, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(20, 600, 371, 171))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_3.setGeometry(QtCore.QRect(10, 60, 221, 31))
        self.comboBox_3.setCurrentText("")
        self.comboBox_3.setObjectName("comboBox_3")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_9.setGeometry(QtCore.QRect(70, 110, 81, 32))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_34 = QtWidgets.QLabel(self.frame_3)
        self.label_34.setGeometry(QtCore.QRect(10, 10, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(650, 210, 521, 261))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.frame_6.setFont(font)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_6)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 511, 251))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self._led3 = LED(self.groupBox_4)
        self._led3.setGeometry(QtCore.QRect(291, 37, 71, 20))
        self._led3.setMaximumSize(QtCore.QSize(16777215, 20))
        self._led3.setObjectName("_led3")
        self.cam_power_on_with_hv = QtWidgets.QPushButton(self.groupBox_4)
        self.cam_power_on_with_hv.setGeometry(QtCore.QRect(133, 33, 241, 32))
        self.cam_power_on_with_hv.setCheckable(False)
        self.cam_power_on_with_hv.setChecked(False)
        self.cam_power_on_with_hv.setObjectName("cam_power_on_with_hv")
        self.cam_power_off = QtWidgets.QPushButton(self.groupBox_4)
        self.cam_power_off.setGeometry(QtCore.QRect(380, 33, 67, 32))
        self.cam_power_off.setObjectName("cam_power_off")
        self.cam_power_on = QtWidgets.QPushButton(self.groupBox_4)
        self.cam_power_on.setGeometry(QtCore.QRect(9, 33, 101, 32))
        self.cam_power_on.setObjectName("cam_power_on")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(15, 71, 481, 161))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.hv_nom_volts_lineedit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.hv_nom_volts_lineedit.setAlignment(QtCore.Qt.AlignCenter)
        self.hv_nom_volts_lineedit.setReadOnly(True)
        self.hv_nom_volts_lineedit.setObjectName("hv_nom_volts_lineedit")
        self.gridLayout_5.addWidget(self.hv_nom_volts_lineedit, 1, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 2, 1, 1)
        self.supply_current_lineedit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.supply_current_lineedit.setAlignment(QtCore.Qt.AlignCenter)
        self.supply_current_lineedit.setReadOnly(True)
        self.supply_current_lineedit.setObjectName("supply_current_lineedit")
        self.gridLayout_5.addWidget(self.supply_current_lineedit, 0, 1, 1, 1)
        self.hv_current_lineedit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.hv_current_lineedit.setAlignment(QtCore.Qt.AlignCenter)
        self.hv_current_lineedit.setReadOnly(True)
        self.hv_current_lineedit.setObjectName("hv_current_lineedit")
        self.gridLayout_5.addWidget(self.hv_current_lineedit, 0, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.supply_nom_volts_lineedit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.supply_nom_volts_lineedit.setAlignment(QtCore.Qt.AlignCenter)
        self.supply_nom_volts_lineedit.setReadOnly(True)
        self.supply_nom_volts_lineedit.setObjectName("supply_nom_volts_lineedit")
        self.gridLayout_5.addWidget(self.supply_nom_volts_lineedit, 1, 1, 1, 1)
        self.supply_meas_volts_lineedit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.supply_meas_volts_lineedit.setAlignment(QtCore.Qt.AlignCenter)
        self.supply_meas_volts_lineedit.setReadOnly(True)
        self.supply_meas_volts_lineedit.setObjectName("supply_meas_volts_lineedit")
        self.gridLayout_5.addWidget(self.supply_meas_volts_lineedit, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 2, 2, 1, 1)
        self.hv_meas_volts_lineedit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.hv_meas_volts_lineedit.setAlignment(QtCore.Qt.AlignCenter)
        self.hv_meas_volts_lineedit.setReadOnly(True)
        self.hv_meas_volts_lineedit.setObjectName("hv_meas_volts_lineedit")
        self.gridLayout_5.addWidget(self.hv_meas_volts_lineedit, 2, 3, 1, 1)
        self.layoutWidget.raise_()
        self.cam_power_on_with_hv.raise_()
        self.cam_power_off.raise_()
        self.cam_power_on.raise_()
        self._led3.raise_()
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 631, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.Currents = QtWidgets.QWidget()
        self.Currents.setObjectName("Currents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Currents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.Currents)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_3.addWidget(self.graphicsView)
        self.tabWidget.addTab(self.Currents, "")
        self.Voltages = QtWidgets.QWidget()
        self.Voltages.setObjectName("Voltages")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Voltages)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.Voltages)
        self.graphicsView_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.verticalLayout_4.addWidget(self.graphicsView_2)
        self.tabWidget.addTab(self.Voltages, "")
        self.Presence = QtWidgets.QWidget()
        self.Presence.setObjectName("Presence")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Presence)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.Presence)
        self.graphicsView_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.verticalLayout_6.addWidget(self.graphicsView_4)
        self.tabWidget.addTab(self.Presence, "")
        self.Temp = QtWidgets.QWidget()
        self.Temp.setObjectName("Temp")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Temp)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.Temp)
        self.graphicsView_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.verticalLayout_5.addWidget(self.graphicsView_3)
        self.tabWidget.addTab(self.Temp, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_5.setGeometry(QtCore.QRect(0, 50, 631, 541))
        self.graphicsView_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 0, 601, 46))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setObjectName("label_7")
        self.gridLayout_9.addWidget(self.label_7, 0, 1, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_14.setFrameShape(QtWidgets.QFrame.Box)
        self.label_14.setObjectName("label_14")
        self.gridLayout_9.addWidget(self.label_14, 0, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_15.setFrameShape(QtWidgets.QFrame.Box)
        self.label_15.setObjectName("label_15")
        self.gridLayout_9.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_31.setFrameShape(QtWidgets.QFrame.Box)
        self.label_31.setObjectName("label_31")
        self.gridLayout_9.addWidget(self.label_31, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_16.setFrameShape(QtWidgets.QFrame.Box)
        self.label_16.setObjectName("label_16")
        self.gridLayout_9.addWidget(self.label_16, 1, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_17.setFrameShape(QtWidgets.QFrame.Box)
        self.label_17.setObjectName("label_17")
        self.gridLayout_9.addWidget(self.label_17, 1, 3, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(650, 100, 521, 101))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_7)
        self.groupBox_2.setGeometry(QtCore.QRect(10, -10, 501, 111))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 21, 501, 81))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self._led2 = LED(self.layoutWidget2)
        self._led2.setMaximumSize(QtCore.QSize(16777215, 20))
        self._led2.setObjectName("_led2")
        self.gridLayout_6.addWidget(self._led2, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_6.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_6.addWidget(self.pushButton_3, 1, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setFrame(True)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_6.addWidget(self.lineEdit_3, 1, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_6.addWidget(self.lineEdit_4, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 2, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(790, 600, 381, 171))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_32 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 1, 1, 1)
        self.Network_lineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.Network_lineEdit.setReadOnly(True)
        self.Network_lineEdit.setObjectName("Network_lineEdit")
        self.gridLayout_3.addWidget(self.Network_lineEdit, 1, 0, 1, 1)
        self.Network_lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.Network_lineEdit_2.setReadOnly(True)
        self.Network_lineEdit_2.setObjectName("Network_lineEdit_2")
        self.gridLayout_3.addWidget(self.Network_lineEdit_2, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 2, 1, 1, 1)
        self.Network_lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.Network_lineEdit_5.setReadOnly(True)
        self.Network_lineEdit_5.setObjectName("Network_lineEdit_5")
        self.gridLayout_3.addWidget(self.Network_lineEdit_5, 3, 0, 1, 1)
        self.Network_lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.Network_lineEdit_6.setReadOnly(True)
        self.Network_lineEdit_6.setObjectName("Network_lineEdit_6")
        self.gridLayout_3.addWidget(self.Network_lineEdit_6, 3, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 4, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 4, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1192, 24))
        self.menuBar.setNativeMenuBar(False)
        self.menuBar.setObjectName("menuBar")
        self.menudihsg = QtWidgets.QMenu(self.menuBar)
        self.menudihsg.setObjectName("menudihsg")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSave_logging = QtWidgets.QAction(MainWindow)
        self.actionSave_logging.setObjectName("actionSave_logging")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menudihsg.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.comboBox_3.setCurrentIndex(-1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SCT Slow Control GUI"))
        self.label_3.setText(_translate("MainWindow", "No connection"))
        self.sysInitializeButton.setText(_translate("MainWindow", "Initialize"))
        self.sysShutdownButton.setText(_translate("MainWindow", "Shutdown"))
        self.shutter_control_groupbox.setTitle(_translate("MainWindow", "Shutter control"))
        self.pushButton_6.setText(_translate("MainWindow", "Open"))
        self.label.setText(_translate("MainWindow", "Motor is On"))
        self.label_2.setText(_translate("MainWindow", "Shutter is closed"))
        self.pushButton_7.setText(_translate("MainWindow", "Close"))
        self.chiller_pressure_label.setText(_translate("MainWindow", "Pressure/Pa"))
        self.chiller_temp_label.setText(_translate("MainWindow", "<html><head/><body><p>Temperature/°F</p></body></html>"))
        self.label_33.setText(_translate("MainWindow", "Chiller"))
        self.pushButton_9.setText(_translate("MainWindow", "Go"))
        self.label_34.setText(_translate("MainWindow", "Backplane"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Camera Power"))
        self.cam_power_on_with_hv.setText(_translate("MainWindow", "ON (w/ HV)"))
        self.cam_power_off.setText(_translate("MainWindow", "OFF"))
        self.cam_power_on.setText(_translate("MainWindow", "ON"))
        self.label_9.setText(_translate("MainWindow", "HV Current/A"))
        self.label_12.setText(_translate("MainWindow", "HV Nom Volts/V"))
        self.label_8.setText(_translate("MainWindow", "Supply Current/A"))
        self.label_11.setText(_translate("MainWindow", "Supply Meas Volts/V"))
        self.label_10.setText(_translate("MainWindow", "Supply Nom Volts/V"))
        self.label_13.setText(_translate("MainWindow", "HV Meas Volts/V"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Currents), _translate("MainWindow", "Currents"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Voltages), _translate("MainWindow", "Voltages"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Presence), _translate("MainWindow", "Presence"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Temp), _translate("MainWindow", "Temp"))
        self.label_4.setText(_translate("MainWindow", "NOTPRESENT   -3"))
        self.label_7.setText(_translate("MainWindow", "NOTPOWERED   -2"))
        self.label_14.setText(_translate("MainWindow", "UNRESPONSIVE    -1"))
        self.label_15.setText(_translate("MainWindow", "UNDEFINED        0"))
        self.label_31.setText(_translate("MainWindow", "PRESYNC            2"))
        self.label_16.setText(_translate("MainWindow", "SAFE          1 "))
        self.label_17.setText(_translate("MainWindow", "READY                     3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Module States"))
        self.label_22.setText(_translate("MainWindow", "Fan"))
        self.label_6.setText(_translate("MainWindow", "Current/A"))
        self.pushButton_2.setText(_translate("MainWindow", "Fans ON"))
        self.pushButton_3.setText(_translate("MainWindow", "Fans OFF"))
        self.label_5.setText(_translate("MainWindow", "Voltage/ V"))
        self.label_32.setText(_translate("MainWindow", "Networks"))
        self.pushButton.setText(_translate("MainWindow", "Check activity"))
        self.label_18.setText(_translate("MainWindow", "ETH6"))
        self.label_19.setText(_translate("MainWindow", "ETH7"))
        self.label_20.setText(_translate("MainWindow", "ETH8"))
        self.label_21.setText(_translate("MainWindow", "ETH9"))
        self.menudihsg.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSave_logging.setText(_translate("MainWindow", "Save logging"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
from sctcamsoft.lib_gui.led import LED
